substitutions:
  name: "current_monitor"
  friendly_name: "Current Monitor"
  
esphome:
  name: "${name}"
  platform: ESP8266
  board: d1_mini
  project:
    name: d1.currentmonitor
    version: "1.0"

# Enable logging
logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "retic-power-monitor"
    
web_server:
  port: 80

sensor:
  - platform: adc
    pin: A0
    name: "24AC Current"
    device_class: current
    unit_of_measurement: lx
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 2.5 -> 0
          # Known load: 4.0A
          # Value shown in logs: 0.1333A
          - 2.685 -> 1.0
      #- filter_out: -13.45017
