esphome:
  name: "${name}"
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: true
  project:
    name: d1.currentmonitor
    version: "1.0"

logger:
api:
ota:



captive_portal:

web_server:
  port: 80

sensor:
  - platform: adc
    pin: A0
    name: "${name}_24AC Current"
    device_class: current
    unit_of_measurement: lx
   # filters:
     # - calibrate_linear:
          # Measured value of 0 maps to 0A
      #    - 2.5 -> 0
          # Known load: 4.0A
          # Value shown in logs: 0.1333A
       #   - 2.685 -> 1.0
      #- filter_out: -13.45017
