substitutions:
  name: "retic-power-monitor"

packages:
  device: !include devices/esp8266.yaml

esphome:
  #name: ${name}
  #name_add_mac_suffix: false
  includes:
    - sensors/ACS712.h

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new ACS712();
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "${name} AC Current Sensor"
    unit_of_measurement: A
    accuracy_decimals: 2
