substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid1: !secret backup_wifi_ssid
  wifi_password1: !secret backup_wifi_password

wifi:
  networks:
  - ssid: "${wifi_ssid}"
    password: "${wifi_password}"
  - ssid: "${wifi_ssid1}"
    password: "${wifi_password1}"
  ap:
    ssid: "${name}"